/**
 * Unit test for the recurring form (src/visuals/motif.js — proposal B2's second
 * attempt, filling the slot D28 left open).
 *
 * D28 removed the first occupant for looking bad and priced a replacement at
 * three constraints. Each has a section below, because "it satisfies the
 * constraints" is exactly the kind of claim that decays into a comment.
 *
 * Run: node --import ./test/register.mjs test/motif.mjs  (included in `npm test`)
 * The register hook is needed only for the FIRST section, which reaches into
 * the music to check that the visuals' cell is still the music's cell.
 */
import {
  growMotif, segmentCount, revealCount, formAt, transformFor,
  MOTIF_CELL, TRANSFORMS, FORM_COSTUME, FORM_SECTIONS, FORM_RISE, FORM_FALL,
} from '../src/visuals/motif.js';
import { MOTIF } from '../src/music/generators.js';
import { SECTION_LAYOUT, TRACKS } from '../src/bus.js';

let failures = 0;
function check(cond, label) {
  if (cond) console.log(`  ok    ${label}`);
  else { failures++; console.error(`  FAIL  ${label}`); }
}

console.log('D28 constraint 3: it is generated by the machinery it is a sibling to');
{
  check(MOTIF_CELL.length === MOTIF.length && MOTIF_CELL.every((d, i) => d === MOTIF[i]),
    'the form grows from the music\'s own cell, note for note');
  // The visuals import nothing from the music (same law that keeps them off the
  // audio), so the two copies are bound by this assertion and nothing else. If
  // it ever fails, the fix is to copy the cell across — not to delete the test.
  check(TRANSFORMS.length === 5, 'five transforms, same as the music\'s 80/20 bag');
  check(TRANSFORMS.find((t) => t.name === 'inversion').apply([0, 2, 4]).join() === '4,2,0',
    'inversion is about the cell\'s own centre (4 − d), as in generators.js');
  check(TRANSFORMS.find((t) => t.name === 'retrograde').apply(MOTIF_CELL).join()
    === [...MOTIF_CELL].reverse().join(), 'retrograde is the cell backwards');
  check(FORM_SECTIONS.every((s) => SECTION_LAYOUT.some(([name]) => name === s)),
    'the section it is spent in is a section the bus actually has');
}

console.log('D28 constraint 1: it reads at 2.5× and at 9× — the rule is the figure');
{
  // The prefix property IS the constraint, operationally: growing the form one
  // level deeper adds detail without moving a line that was already there, so
  // depth is a zoom level rather than a different drawing. A hand-placed point
  // list — the moth — cannot have this, which is why it had exactly one scale.
  let prefix = true;
  for (let d = 1; d < 8; d++) {
    const a = growMotif(MOTIF_CELL, { depth: d });
    const b = growMotif(MOTIF_CELL, { depth: d + 1 });
    if (b.length < a.length) { prefix = false; break; }
    for (let i = 0; i < a.length; i++) if (Math.abs(a[i] - b[i]) > 1e-9) { prefix = false; break; }
    if (!prefix) break;
  }
  check(prefix, 'grow(d+1) begins with exactly grow(d): depth is zoom, not a redraw');

  const scales = FORM_COSTUME.map((c) => c.scale);
  check(Math.min(...scales) === 2.5 && Math.max(...scales) === 9,
    'the costume spends D28\'s own two numbers as its extremes');
  let depthTracksScale = true;
  const sorted = [...FORM_COSTUME].sort((p, q) => p.scale - q.scale);
  for (let i = 1; i < sorted.length; i++) if (sorted[i].depth < sorted[i - 1].depth) depthTracksScale = false;
  check(depthTracksScale, 'the bigger it is drawn the deeper it is grown — more of the same rule');

  for (let d = 1; d <= 8; d++) {
    const segs = growMotif(MOTIF_CELL, { depth: d });
    if (segs.length !== segmentCount(d) * 6) { check(false, `depth ${d} fills its buffer exactly`); break; }
    if (d === 8) check(true, 'every depth fills its buffer exactly (2^(d+1) − 2 segments)');
  }
  const deep = growMotif(MOTIF_CELL, { depth: 8 });
  check(deep.every(Number.isFinite), 'no NaN anywhere in the deepest form');
  check(segmentCount(8) === 510, 'the largest costume is 510 segments — a rule is cheap');

  // A degenerate cell must not collapse the figure into a point or a line.
  const flat = growMotif([0, 0, 0, 0, 0, 0, 0, 0], { depth: 5 });
  let span = 0;
  for (let i = 0; i < flat.length; i += 3) span = Math.max(span, Math.hypot(flat[i], flat[i + 1], flat[i + 2]));
  check(span > 0.5, 'a cell of all-zero degrees still grows (length is bounded away from 0)');
}

console.log('D28 constraint 2: figure by edge, never by rhythm');
{
  const base = { section: 'peak', trackIndex: 1, t: 100, drift: 0, seed: 7 };
  check(formAt({ ...base }).target === 1, 'present in the peak section');
  for (const [name] of SECTION_LAYOUT) {
    if (FORM_SECTIONS.includes(name)) continue;
    if (formAt({ ...base, section: name }).target !== 0) {
      check(false, `absent outside peak (saw it in ${name})`); break;
    }
    if (name === 'release') check(true, 'absent in every other section, and in the seam');
  }
  check(formAt({ ...base, section: 'seam' }).target === 0, 'absent across the boundary too');

  // Continuity in time is what proves it cannot be articulating anything: a
  // figure that moves smoothly through every 16th cannot be landing on one.
  // (Everything the form reads is the clock, the section and the track — there
  // is no entry point here that takes an event, and there is no way to add one
  // without this file noticing the discontinuity it would cause.)
  let maxJump = 0, prev = formAt({ ...base, t: 0 });
  for (let i = 1; i <= 4000; i++) {
    const s = formAt({ ...base, t: i * 0.01 }); // 100 Hz over 40 s
    maxJump = Math.max(maxJump,
      Math.abs(s.pos.x - prev.pos.x), Math.abs(s.pos.y - prev.pos.y),
      Math.abs(s.pos.z - prev.pos.z), Math.abs(s.spin - prev.spin));
    prev = s;
  }
  check(maxJump < 0.01, `continuous in time (largest step over 40 s: ${maxJump.toFixed(5)})`);

  // "Absent outside peak" is a claim about how fast the presence FALLS, not
  // just about what `target` says. A single symmetric rate took ~25 s to fade
  // from grown to invisible and left half a form standing in the release
  // section — measured as fine and photographed as wrong. Both rates are
  // exponential, so the time to fall from 1 to invisible (~0.001) is
  // ln(1000)/rate seconds.
  const secondsToVanish = Math.log(1000) / FORM_FALL;
  check(secondsToVanish < 10,
    `gone within the section it left (${secondsToVanish.toFixed(1)} s from fully grown)`);
  check(FORM_FALL > FORM_RISE * 2,
    'and it withdraws faster than it arrives — growing is work, stopping is not');
  check(FORM_FALL < 40,
    'but never in one frame: a form that vanishes on a frame has articulated that frame');

  check(revealCount(6, 0) === 0 && revealCount(6, 1) === segmentCount(6),
    'the reveal runs from nothing to the whole form');
  let monotone = true, last = -1;
  for (let i = 0; i <= 100; i++) {
    const c = revealCount(6, i / 100);
    if (c < last) monotone = false;
    last = c;
  }
  check(monotone, 'and only ever grows — coarse-to-fine, trunk first');
}

console.log('the institution: four appearances, one cell, four transforms');
{
  let allDistinct = true, worstSeed = null;
  for (let seed = 0; seed < 400; seed++) {
    const names = TRACKS.map((_, i) => transformFor(i, seed).name);
    if (new Set(names).size !== TRACKS.length) { allDistinct = false; worstSeed = seed; break; }
  }
  check(allDistinct,
    `no two tracks ever wear the same transform, on any seed${worstSeed == null ? '' : ` (failed at ${worstSeed})`}`);
  // Four tracks and five transforms is why that holds: the set walks a window
  // of four consecutive entries and the seed only chooses where it starts —
  // the same rotation argument D38 used for the seam materials.
  check(TRANSFORMS.length > TRACKS.length, 'more transforms than tracks, which is what makes it provable');

  check(FORM_COSTUME.length === TRACKS.length, 'one costume per track');
  const cells = TRACKS.map((_, i) => formAt({ section: 'peak', trackIndex: i, seed: 11 }).cell);
  check(cells.every((c) => c.length === MOTIF_CELL.length),
    'every appearance is the same eight notes, transformed — never new material');
}

console.log(failures ? `\n${failures} failure(s)` : '\nall good');
process.exit(failures ? 1 : 0);
