/**
 * motif.js — the recurring form, and the second attempt at the slot D28 left
 * open. Pure: no three.js, no state, no DOM, so every claim below is an
 * assertion in `test/motif.mjs` rather than a paragraph in a design doc.
 *
 * The argument for the slot (visualizer_theory §5) never went away: the set has
 * ONE melodic cell (`MOTIF` in generators.js), recalled under transformation
 * across four tracks, and repetition under transformation is what turns a
 * sequence of tracks into an argument. The eye was owed the same sentence. What
 * failed was the moth — a couple of dozen hand-placed line segments of a
 * literal creature, which reads as clip-art at every scale it is drawn at.
 *
 * D28 priced a replacement at three constraints, and this module is shaped by
 * them rather than merely compatible with them:
 *
 *   1. *It must read at 2.5× and at 9×.* So the form is not a drawing, it is a
 *      RULE — a depth-limited growth. Zoom is depth: the costume table below
 *      literally spends 2.5 and 9 as its extreme scales, and the deeper the
 *      form is grown the more of the same rule you see. Segments are emitted
 *      breadth-first, so growing one level deeper never moves a line that was
 *      already there (`growMotif` prefix property, asserted). That is what
 *      "self-similar" has to mean operationally, and a hand-placed point list
 *      can never have it.
 *   2. *It must be figure by edge, not by rhythm* (§2.1). Nothing here takes an
 *      event. `formAt` is a function of the section, the track and the clock;
 *      it is continuous in time by construction, and the test measures that.
 *      The form is figure because it is hard-edged, white and near — the same
 *      way the kick rings are — never because it lands on anything.
 *   3. *It must be generated by the same machinery it is a sibling to.* The
 *      cell IS the music's cell, and the four appearances wear four of the
 *      music's own five transforms. `test/motif.mjs` imports `MOTIF` from
 *      generators.js and fails if the two ever drift apart, which is the only
 *      way "the same cell" stays true rather than becoming a comment.
 *
 * What the rule draws: a binary growth whose branch ANGLES come from the
 * intervals of the cell (what the motif does) and whose branch PLANES come from
 * its degrees (where the motif sits). Two children per node read two different
 * windows of the eight-note cell, so one short cell fills a whole tree without
 * ever repeating a node's neighbourhood — the same trick the music plays when
 * eight notes fill eleven minutes.
 */

const clamp01 = (x) => (x < 0 ? 0 : x > 1 ? 1 : x);

/**
 * The set's single cell — scale-degree offsets. This is a COPY of `MOTIF` in
 * `src/music/generators.js`, deliberately: the visuals import nothing from the
 * music (the same law that keeps them off the audio), so the binding is a test
 * instead of an import. `test/motif.mjs` fails if the two diverge.
 */
export const MOTIF_CELL = [0, 2, 1, 4, 3, 2, 4, 0];

/**
 * The music's 80/20 bag, restated as pure functions of (cell, k) rather than
 * of an rng — the visuals need the same transform to come back for the same
 * track on the same seed, and a shared rng stream would make that an accident
 * of call order. Same five operations, same inversion axis (`4 - d`).
 */
export const TRANSFORMS = [
  { name: 'literal', apply: (m) => m.slice() },
  { name: 'retrograde', apply: (m) => [...m].reverse() },
  { name: 'inversion', apply: (m) => m.map((d) => 4 - d) },
  { name: 'rotation', apply: (m, k) => m.map((_, i) => m[(i + 1 + (k % (m.length - 1))) % m.length]) },
  { name: 'transposition', apply: (m, k) => m.map((d) => d + 1 + (k % 2)) },
];

/** The transform this track wears, chosen by track index and rotated by seed. */
export function transformFor(trackIndex, seed = 0) {
  const off = Math.abs(Math.round(seed)) % TRANSFORMS.length;
  return TRANSFORMS[(trackIndex + off) % TRANSFORMS.length];
}

// ---------- the growth rule ----------

// Golden ratio, which is what everything in this world shrinks by: the set's
// climax sits at 0.618 of it, the shells that used to be the sky were nested at
// it, and a growth that halved would read as a diagram of halving.
const RATIO = 0.618;

/**
 * Grow the form. Returns a flat Float32Array of line-segment endpoints
 * (x0,y0,z0, x1,y1,z1, …) in a local frame with the base at the origin and the
 * trunk pointing +y.
 *
 * Segments are emitted BREADTH-FIRST — every segment of depth d precedes every
 * segment of depth d+1. Two consequences, and both are load-bearing:
 *   • `grow(depth+1)` begins with exactly `grow(depth)`, so depth is a zoom
 *     level rather than a different figure (D28's first constraint);
 *   • the renderer can reveal the form by drawing a prefix of the buffer, so
 *     "it grows" costs a draw range rather than a rebuild, and it grows
 *     coarse-to-fine, which is the only order in which growth reads as growth.
 */
export function growMotif(cell = MOTIF_CELL, opts = {}) {
  const depth = Math.max(1, Math.min(10, Math.round(opts.depth ?? 5)));
  const length = opts.length ?? 1;
  const ratio = opts.ratio ?? RATIO;
  const spread = opts.spread ?? 0.62; // radians per unit of interval
  const n = cell.length;

  const segs = new Float32Array(segmentCount(depth) * 6);
  let out = 0;

  // a turtle: where it is, where it points, and which window of the cell it
  // is reading. The cell index is what makes two branches of the same depth
  // different from each other.
  let queue = [{ x: 0, y: 0, z: 0, dx: 0, dy: 1, dz: 0, idx: 0 }];
  for (let d = 0; d < depth; d++) {
    const next = [];
    for (const t of queue) {
      const a = cell[((t.idx % n) + n) % n];
      const b = cell[(((t.idx + 1) % n) + n) % n];
      const iv = b - a; // the INTERVAL — what the cell does, not where it sits

      // Segment length carries the cell's contour as well as its intervals, so
      // the figure states the tune in two ways at once and a listener who knows
      // the cell can see it. Bounded well away from zero: a degree of 0 must
      // shorten a branch, never delete it.
      const len = length * Math.pow(ratio, d) * (0.62 + (a / 4) * 0.76);
      const theta = spread * (0.4 + Math.abs(iv) * 0.42);
      const phi = (a / 4) * Math.PI * 2; // the branch PLANE, from the degree

      // an orthonormal pair spanning the plane perpendicular to the heading
      const { ux, uy, uz, vx, vy, vz } = perp(t.dx, t.dy, t.dz);
      const ax = ux * Math.cos(phi) + vx * Math.sin(phi);
      const ay = uy * Math.cos(phi) + vy * Math.sin(phi);
      const az = uz * Math.cos(phi) + vz * Math.sin(phi);

      for (const sign of [1, -1]) {
        const dir = rotate(t.dx, t.dy, t.dz, ax, ay, az, theta * sign);
        const x1 = t.x + dir.x * len, y1 = t.y + dir.y * len, z1 = t.z + dir.z * len;
        segs[out++] = t.x; segs[out++] = t.y; segs[out++] = t.z;
        segs[out++] = x1; segs[out++] = y1; segs[out++] = z1;
        // the two children read two different windows of the cell: +1 and +2,
        // coprime with 8's factors in the way that matters — no node's
        // neighbourhood recurs anywhere else in the tree at this depth
        next.push({ x: x1, y: y1, z: z1, dx: dir.x, dy: dir.y, dz: dir.z, idx: t.idx + (sign > 0 ? 1 : 2) });
      }
    }
    queue = next;
  }
  return segs;
}

/**
 * Segments in a form of this depth. Every node branches in two, so level d
 * carries 2^(d+1) segments and the tree totals 2^(depth+1) − 2: 62 at the
 * smallest costume, 510 at the largest. A few hundred lines is nothing to draw
 * and is the reason the form can afford to be a rule rather than a sprite.
 */
export function segmentCount(depth) {
  return (1 << (Math.max(1, Math.min(10, Math.round(depth))) + 1)) - 2;
}

/** Rodrigues rotation of the unit vector d about the unit axis a by `ang`. */
function rotate(dx, dy, dz, ax, ay, az, ang) {
  const c = Math.cos(ang), s = Math.sin(ang);
  const dot = ax * dx + ay * dy + az * dz;
  const cx = ay * dz - az * dy, cy = az * dx - ax * dz, cz = ax * dy - ay * dx;
  let x = dx * c + cx * s + ax * dot * (1 - c);
  let y = dy * c + cy * s + ay * dot * (1 - c);
  let z = dz * c + cz * s + az * dot * (1 - c);
  const m = Math.hypot(x, y, z) || 1;
  return { x: x / m, y: y / m, z: z / m };
}

/** Two unit vectors spanning the plane perpendicular to (dx,dy,dz). */
function perp(dx, dy, dz) {
  // a reference that is never parallel to the heading, so the cross never dies
  const rx = Math.abs(dy) > 0.9 ? 1 : 0, ry = Math.abs(dy) > 0.9 ? 0 : 1, rz = 0;
  let ux = dy * rz - dz * ry, uy = dz * rx - dx * rz, uz = dx * ry - dy * rx;
  const mu = Math.hypot(ux, uy, uz) || 1;
  ux /= mu; uy /= mu; uz /= mu;
  const vx = dy * uz - dz * uy, vy = dz * ux - dx * uz, vz = dx * uy - dy * ux;
  return { ux, uy, uz, vx, vy, vz };
}

// ---------- the costume: four appearances, one form ----------
// B2's original acceptance criterion, unchanged: the same form recognizable in
// all four tracks, absent outside peak sections. What changed is what "the same
// form" means — not the same drawing under a colour, but the same RULE under a
// transform of the same cell, at scales an order of magnitude apart.
//
// The scales are D28's own numbers. It asked for something that reads at 2.5×
// and at 9×; these are those, spent on the two tracks where they mean the most —
// small and close among the litter where the world is metres deep, vast and
// overhead at the canopy climax where it is the only thing with a horizon
// behind it. Depth follows scale, because at 9× the eye can resolve two more
// generations of the rule and at 2.5× it cannot: same figure, more of it.
// `rise` is where the form's CENTRE sits above the eye, not where its base
// does — the renderer centres the growth on its own bounding box, because the
// rule's height is a function of the cell and a base offset that frames one
// transform hangs the next one out of shot. Kept small: a figure the eye has to
// look up at is a figure the eye can miss.
export const FORM_COSTUME = [
  { scale: 2.5, depth: 5, rise: 1.0, dist: 11, spin: 0.021 }, // undergrowth: small, close, low
  { scale: 4.0, depth: 6, rise: 1.5, dist: 15, spin: 0.013 }, // understory:  between the trunks
  { scale: 9.0, depth: 8, rise: 2.5, dist: 26, spin: 0.008 }, // canopy:      vast and overhead
  { scale: 6.0, depth: 7, rise: 2.0, dist: 22, spin: 0.005 }, // open air:    wide, far, slow
];

/** The section the form is spent in, and nowhere else, ever. */
export const FORM_SECTIONS = ['peak'];

// How fast the presence follows its target, per second. The two rates are
// deliberately different, and the asymmetry was a bug before it was a decision:
// a single 0.28 rate takes ~25 s to fall from grown to invisible, so the first
// version was still drawing half a form well into the *release* section — which
// fails B2's acceptance criterion (absent outside peak) by a wide margin, and
// was invisible in every measurement and obvious in one screenshot.
//
// It still cannot CUT — a form that vanishes on a frame has articulated that
// frame, which is the one thing D28 says it must never do. So it withdraws
// about three times faster than it arrives, which is also the honest shape for
// a growth: growing is work and stopping is not. The draw range does the rest,
// retreating twig-first because the buffer is breadth-first.
export const FORM_RISE = 0.28; // ~4 s to grown
export const FORM_FALL = 0.9;  // ~3 s to gone

/**
 * The form's state this frame. Pure, continuous, and eventless.
 *
 * env = { section, trackIndex, t, drift, seed }
 * → { on, target, scale, depth, transform, cell, pos:{x,y,z}, spin }
 *
 * `target` is 0 or 1: the caller smooths it, exactly as it smooths the ink
 * style, because a section boundary is a hard edge and a form that snaps into
 * existence is an event — which would make it rhythm, which is the one thing
 * D28 says it must never be. Everything else here is continuous in `t`.
 */
export function formAt(env = {}) {
  const i = Math.max(0, Math.min(FORM_COSTUME.length - 1, env.trackIndex ?? 0));
  const c = FORM_COSTUME[i];
  const tf = transformFor(i, env.seed ?? 0);
  const t = env.t ?? 0;
  const drift = env.drift ?? 0;
  const on = FORM_SECTIONS.includes(env.section);

  // Where it hangs: ahead of the camera, a little above the eye, drifting on
  // the same 1/f the whole world breathes with. Never centred — a figure in the
  // middle of the frame is a logo — and always to the LEFT, because the perform
  // rail's panel owns the right quarter of the window and a form that wanders
  // behind it is a form that is sometimes not there.
  const ang = t * c.spin * Math.PI * 2;
  return {
    on,
    target: on ? 1 : 0,
    cell: tf.apply(MOTIF_CELL, i),
    transform: tf.name,
    scale: c.scale,
    depth: c.depth,
    spin: ang,
    pos: {
      x: (-0.22 + 0.10 * Math.cos(ang * 0.7)) * c.dist + drift * 1.2,
      y: c.rise,
      z: -c.dist,
    },
  };
}

/**
 * How much of the form is drawn at reveal amount `a` — a segment count, so the
 * renderer sets a draw range instead of rebuilding geometry. Coarse-to-fine by
 * the breadth-first order: the trunk arrives first and the twigs last, which is
 * the only order in which appearing reads as growing rather than as fading in.
 */
export function revealCount(depth, a) {
  return Math.round(segmentCount(depth) * smooth(clamp01(a)));
}

const smooth = (x) => x * x * (3 - 2 * x);
